server.servlet.context-path=/api

app.version=${project.version}

logging.level.com.keithlawless.jukebox.services.SearchService=WARN
logging.level.com.keithlawless.jukebox.services.TagService=WARN
logging.level.com.keithlawless.jukebox.services.FileService=WARN
logging.level.org.jaudiotagger=WARN

com.keithlawless.jukebox.controllers.autoplay=true
com.keithlawless.jukebox.basedir=file:///Users/keithlawless/Music/
com.keithlawless.jukebox.filefilter=mp3,flac,m4a
com.keithlawless.jukebox.default.image=/images/notfound.jpg
com.keithlawless.jukebox.station.data=/data/stations.json
com.keithlawless.jukebox.search.index.location=/Users/keithlawless/var/jukebox/index

com.keithlawless.jukebox.spotify.librespot.path=/usr/local/bin/librespot
com.keithlawless.jukebox.spotify.device.name=Jukebox
com.keithlawless.jukebox.spotify.backend=alsa
com.keithlawless.jukebox.spotify.device=plughw:Device,0
com.keithlawless.jukebox.spotify.bitrate=320
com.keithlawless.jukebox.spotify.cache=/var/cache/librespot

